<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ZenBoxUI.Components\ZenBoxUI.Blazor.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\bootstrap\" />
  </ItemGroup>

</Project>
