<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="Components\Pages\Components\InputNumber\CodeSnippets\InputNumberNullText.razor.txt" />
    <Content Include="Components\Pages\Components\InputNumber\CodeSnippets\InputNumberBind.razor.txt" />
    <Content Include="Components\Pages\Components\InputNumber\CodeSnippets\InputNumberClearButton.razor.txt" />
    <Content Include="Components\Pages\Components\InputNumber\CodeSnippets\InputNumberDisabled.razor.txt" />
    <Content Include="Components\Pages\Components\InputNumber\CodeSnippets\InputNumberEvents.razor.txt" />
    <Content Include="Components\Pages\Components\InputNumber\CodeSnippets\InputNumberEventsToasts.cs.txt" />
    <Content Include="Components\Pages\Components\InputNumber\CodeSnippets\InputNumberValidationCp.razor.txt" />
    <Content Include="Components\Pages\Components\InputText\CodeSnippets\InputTextNullText.razor.txt" />
    <Content Include="Components\Pages\Components\InputText\CodeSnippets\InputTextBind.razor.txt" />
    <Content Include="Components\Pages\Components\InputText\CodeSnippets\InputTextClearButton.razor.txt" />
    <Content Include="Components\Pages\Components\InputText\CodeSnippets\InputTextDisabled.razor.txt" />
    <Content Include="Components\Pages\Components\InputText\CodeSnippets\InputTextEvents.razor.txt" />
    <Content Include="Components\Pages\Components\InputText\CodeSnippets\InputTextEventsToasts.cs.txt" />
    <Content Include="Components\Pages\Components\InputText\CodeSnippets\InputTextPassword.razor.txt" />
    <Content Include="Components\Pages\Components\InputText\CodeSnippets\InputTextValidationCp.razor.txt" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="HighlightBlazor" Version="0.1.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ZenBoxUI.Components\ZenBoxUI.Blazor.csproj" />
  </ItemGroup>

</Project>
